workflows:
  ios-build:
    name: Build Element iOS 1.11.25
    environment:
      vars:
        XCODE_PROJECT: "Riot.xcodeproj"
        XCODE_SCHEME: "Element"
      xcode: latest
      cocoapods: default
    scripts:
      - name: 安裝 CocoaPods 依賴
        script: |
          gem install cocoapods
          pod install
      - name: Build .ipa
        script: |
          xcodebuild -project $XCODE_PROJECT \
                     -scheme $XCODE_SCHEME \
                     -sdk iphoneos \
                     -configuration Release \
                     -derivedDataPath build \
                     clean build
    artifacts:
      - build/Build/Products/Release-iphoneos/*.app
      - build/**/*.dSYM
      - build/**/*.ipa
