workflows:
  element-ios-workflow:
    name: Element iOS Build
    instance_type: mac_mini_m1  # M1 芯片加速构建
    environment:
      groups:
        - ios_signing  # 包含加密的证书/配置文件
    triggering:
      events:
        - push
    scripts:
      - name: Setup
        script: |
          # 安装依赖
          brew install xcodegen
          gem install cocoapods
          
          # 生成 Xcode 项目
          xcodegen
          pod install
          
      - name: Build
        script: |
          xcodebuild build-for-testing \
            -workspace "Riot.xcworkspace" \
            -scheme "Riot" \
            -destination 'platform=iOS Simulator,name=iPhone 15'
      
      - name: Test (可选)
        script: |
          xcode-project run-tests \
            --workspace "Riot.xcworkspace" \
            --scheme "Riot" \
            --device "iPhone 15"
        test_report: build/ios/test/*.xml  # 集成测试报告
    artifacts:
      - build/**/*.app  # 输出产物
