workflows:
  unsigned-build:
    name: Build unsigned iOS app
    environment:
      xcode: "15.2"
    scripts:
      - name: Install Pods (using system CocoaPods)
        script: |
          pod install
      - name: Clean build
        script: |
          xcodebuild clean -workspace mygodelement.xcworkspace \
                           -scheme mygodelement \
                           -configuration Release \
                           CODE_SIGN_IDENTITY="" \
                           CODE_SIGNING_REQUIRED=NO \
                           CODE_SIGNING_ALLOWED=NO
      - name: Build unsigned .app
        script: |
          xcodebuild build -workspace mygodelement.xcworkspace \
                           -scheme mygodelement \
                           -configuration Release \
                           -sdk iphoneos \
                           CODE_SIGN_IDENTITY="" \
                           CODE_SIGNING_REQUIRED=NO \
                           CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/Release-iphoneos/*.app