workflows:
  ios-build:
    name: Build Element iOS 1.11.25
    environment:
      vars:
        XCODE_WORKSPACE: "Riot.xcworkspace"
        XCODE_SCHEME: "Riot"
      xcode: latest
      cocoapods: default
    scripts:
      - name: 安裝 CocoaPods 依賴
        script: |
          gem install cocoapods
          pod install
      - name: Build .ipa
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -configuration Release -archivePath $CM_BUILD_DIR/$XCODE_SCHEME.xcarchive archive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/$XCODE_SCHEME.xcarchive -exportPath $CM_BUILD_DIR -exportOptionsPlist ExportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/*.dSYM.zip
      - $CM_BUILD_DIR/export_logs/*.log
      - $CM_BUILD_DIR/xcarchive.zip
